### ISSUE TITLE
Errors with StatusCallback

### ISSUE THREAD

**Issue by zorbaskyriakos** [crownstone/crownstone-dev#1]
Hello i would like to test the crownstone-dev because recently i bought some crownstones!!
I followed exactly the steps to import it to android studio but unfortunately when i am going to Generate the Signed apk for testing the app with my smartphone it gives me the following errors!! I did something wrong?Thanks for the help!!

Information:Gradle tasks [:app:assembleRelease]
C:\Users\Kyriakos\Desktop\crownstone-dev\app\src\main\java\nl\dobots\crownstone\CrownstoneDevApp.java
Error:(36, 44) error: cannot find symbol class IStatusCallback
Error:(367, 82) error: cannot find symbol class IStatusCallback
Error:(436, 101) error: cannot find symbol class IStatusCallback
Error:(144, 24) error: cannot find symbol class IStatusCallback
Error:(499, 12) error: cannot find symbol class IStatusCallback
C:\Users\Kyriakos\Desktop\crownstone-dev\app\src\main\java\nl\dobots\crownstone\gui\control\ControlActivity.java
Error:(23, 44) error: cannot find symbol class IStatusCallback
Error:(236, 42) error: cannot find symbol class IStatusCallback
Error:(254, 42) error: cannot find symbol class IStatusCallback
C:\Users\Kyriakos\Desktop\crownstone-dev\app\src\main\java\nl\dobots\crownstone\gui\control\ControlMainFragment.java
Error:(29, 44) error: cannot find symbol class IStatusCallback
Error:(255, 39) error: cannot find symbol class IStatusCallback
Error:(346, 56) error: cannot find symbol variable layStatistics
Error:(432, 42) error: cannot find symbol class IStatusCallback
Error:(467, 43) error: cannot find symbol class IStatusCallback
Error:(527, 47) error: cannot find symbol class IStatusCallback
Error:(555, 47) error: cannot find symbol class IStatusCallback
Error:(585, 31) error: cannot find symbol class IStatusCallback
Error:(617, 30) error: cannot find symbol class IStatusCallback
Error:(699, 33) error: cannot find symbol class IStatusCallback
Error:(730, 32) error: cannot find symbol class IStatusCallback
Error:(761, 38) error: cannot find symbol class IStatusCallback
C:\Users\Kyriakos\Desktop\crownstone-dev\app\src\main\java\nl\dobots\crownstone\gui\control\ControlMeasurementsFragment.java
Error:(29, 44) error: cannot find symbol class IStatusCallback
Error:(253, 36) error: cannot find symbol class IStatusCallback
C:\Users\Kyriakos\Desktop\crownstone-dev\app\src\main\java\nl\dobots\crownstone\gui\MainActivity.java
Error:(23, 44) error: cannot find symbol class IStatusCallback
Error:(291, 9) error: cannot find symbol class IStatusCallback
Error:(319, 10) error: cannot find symbol class IStatusCallback
C:\Users\Kyriakos\Desktop\crownstone-dev\app\src\main\java\nl\dobots\crownstone\gui\SelectControlFragment.java
Error:(20, 44) error: cannot find symbol class IStatusCallback
Error:(277, 56) error: cannot find symbol class IStatusCallback
Error:(109, 31) error: cannot find symbol class IStatusCallback
Error:(170, 65) error: cannot find symbol class IStatusCallback
Error:(241, 50) error: cannot find symbol class IStatusCallback
Error:(278, 48) error: cannot find symbol class IStatusCallback
Error:Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 15.062 secs
Information:32 errors
Information:0 warnings
Information:See complete output in console

**Comment by mrquincle** [comment]
Hi Kyriakos!

Thanks for reporting the issues. My colleagues will probably join in on Monday. However, to get it started. Are you aware this is a development app?

The recommended combination is:

- https://github.com/crownstone/bluenet-lib-android
- https://github.com/crownstone/CrownstoneApp

It looks much better than the development app! :-)

Greetings, 

Anne

**Comment by zorbaskyriakos** [comment]
Yes i know that it's a development app, ok i will wait for your colleagues in the meantime i will try to figure it out by my own , to see if its my fault that it doesn't work!! thank you again for your response :)

**Comment by vliedel** [comment]
Hi zorbaskyriakos, I got these errors too last friday. Probably due to some commit gone wrong. I will commit my fix tomorrow :)
This app may actually be a good starting point for you, as it includes the cloud side as well.

**Comment by vliedel** [comment]
Should be fixed now by https://github.com/crownstone/crownstone-dev/commit/962738d5a6e974f4af18f26a436907c5637d801e.

**Comment by zorbaskyriakos** [comment]
Yes now it works thank you very much!!
